[2024-09-19T05:04:47.118+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T05:04:47.137+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T05:03:20.756602+00:00 [queued]>
[2024-09-19T05:04:47.146+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T05:03:20.756602+00:00 [queued]>
[2024-09-19T05:04:47.146+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-19T05:04:47.161+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): run_data_processing> on 2024-09-19 05:03:20.756602+00:00
[2024-09-19T05:04:47.170+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nba_data_pipeline', 'run_data_processing', 'manual__2024-09-19T05:03:20.756602+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmp8njoc36y']
[2024-09-19T05:04:47.173+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask run_data_processing
[2024-09-19T05:04:47.175+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=324) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-19T05:04:47.176+0000] {standard_task_runner.py:72} INFO - Started process 325 to run task
[2024-09-19T05:04:47.228+0000] {task_command.py:467} INFO - Running <TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T05:03:20.756602+00:00 [running]> on host e600337142de
[2024-09-19T05:04:47.345+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T05:03:20.756602+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-19T05:03:20.756602+00:00'
[2024-09-19T05:04:47.346+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T05:04:47.350+0000] {baseoperator.py:405} WARNING - DockerOperator.execute cannot be called outside TaskInstance!
[2024-09-19T05:04:47.379+0000] {docker.py:367} INFO - Starting docker container from image us-west1-docker.pkg.dev/nba-fantasy-ml/nba-data-pipeline-repo/data-processing:latest
[2024-09-19T05:04:47.389+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-19T05:04:48.265+0000] {docker.py:438} INFO - 2024-09-19 05:04:48,264 - ERROR - An error occurred during data processing: expected string or bytes-like object
[2024-09-19T05:04:48.448+0000] {python.py:240} INFO - Done. Returned value was: 2024-09-19 05:04:48,264 - ERROR - An error occurred during data processing: expected string or bytes-like object
[2024-09-19T05:04:48.472+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T05:04:48.473+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=run_data_processing, run_id=manual__2024-09-19T05:03:20.756602+00:00, execution_date=20240919T050320, start_date=20240919T050447, end_date=20240919T050448
[2024-09-19T05:04:48.506+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T05:04:48.524+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-19T05:04:48.526+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
