[2024-09-18T21:32:41.614+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-18T21:32:41.632+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-18T21:32:41.640+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-18T21:32:41.641+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-18T21:32:41.652+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): run_data_processing> on 2024-09-17 00:00:00+00:00
[2024-09-18T21:32:41.661+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nba_data_pipeline', 'run_data_processing', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmphrhlrize']
[2024-09-18T21:32:41.664+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_data_processing
[2024-09-18T21:32:41.665+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-18T21:32:41.666+0000] {standard_task_runner.py:72} INFO - Started process 256 to run task
[2024-09-18T21:32:41.713+0000] {task_command.py:467} INFO - Running <TaskInstance: nba_data_pipeline.run_data_processing scheduled__2024-09-17T00:00:00+00:00 [running]> on host ce65ca4e65cd
[2024-09-18T21:32:41.793+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-17T00:00:00+00:00'
[2024-09-18T21:32:41.795+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-18T21:32:41.813+0000] {cleaning.py:279} INFO - Starting data processing...
[2024-09-18T21:32:41.817+0000] {cleaning.py:289} INFO - Database connected.
[2024-09-18T21:32:41.818+0000] {cleaning.py:292} INFO - Cleaning and preprocessing data...
[2024-09-18T21:32:41.853+0000] {validate.py:58} INFO - Validation passed.
[2024-09-18T21:32:41.853+0000] {cleaning.py:305} INFO - Assigning unique IDs for players and games...
[2024-09-18T21:32:41.872+0000] {cleaning.py:310} INFO - Inserting player stats into database...
[2024-09-18T21:32:41.877+0000] {cleaning.py:314} ERROR - Error processing raw data: duplicate key value violates unique constraint "playerstats_pkey"
DETAIL:  Key (game_id, player_id)=(35cb0b0af43f4774b3a236ef2275d790, 1) already exists.

[2024-09-18T21:32:41.878+0000] {cleaning.py:318} INFO - Database connection closed.
[2024-09-18T21:32:41.879+0000] {main.py:36} INFO - Successfully processed player_box_scores/2023-24/nba_player_stats_2023-24_2024-06-01_to_2024-06-30_2024-09-18_21-27-00.csv
[2024-09-18T21:32:41.880+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-18T21:32:41.888+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-18T21:32:41.889+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=run_data_processing, run_id=scheduled__2024-09-17T00:00:00+00:00, execution_date=20240917T000000, start_date=20240918T213241, end_date=20240918T213241
[2024-09-18T21:32:41.935+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-18T21:32:41.954+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-18T21:32:41.956+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-18T21:59:58.313+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-18T21:59:58.332+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-18T21:59:58.346+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-18T21:59:58.346+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-18T21:59:58.361+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): run_data_processing> on 2024-09-17 00:00:00+00:00
[2024-09-18T21:59:58.370+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nba_data_pipeline', 'run_data_processing', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmp1zdq76ot']
[2024-09-18T21:59:58.374+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask run_data_processing
[2024-09-18T21:59:58.376+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-18T21:59:58.377+0000] {standard_task_runner.py:72} INFO - Started process 233 to run task
[2024-09-18T21:59:58.429+0000] {task_command.py:467} INFO - Running <TaskInstance: nba_data_pipeline.run_data_processing scheduled__2024-09-17T00:00:00+00:00 [running]> on host e4c1837770e9
[2024-09-18T21:59:58.524+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-17T00:00:00+00:00'
[2024-09-18T21:59:58.526+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-18T21:59:58.535+0000] {main.py:28} ERROR - No CSV files found in the bucket. Exiting...
[2024-09-18T21:59:58.536+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-18T21:59:58.546+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-18T21:59:58.547+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=run_data_processing, run_id=scheduled__2024-09-17T00:00:00+00:00, execution_date=20240917T000000, start_date=20240918T215958, end_date=20240918T215958
[2024-09-18T21:59:58.601+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-18T21:59:58.619+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-18T21:59:58.621+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
