[2024-09-19T09:28:01.747+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T09:28:01.766+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T09:13:25.420482+00:00 [queued]>
[2024-09-19T09:28:01.776+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T09:13:25.420482+00:00 [queued]>
[2024-09-19T09:28:01.777+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 6
[2024-09-19T09:28:01.792+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_data_processing> on 2024-09-19 09:13:25.420482+00:00
[2024-09-19T09:28:01.800+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nba_data_pipeline', 'run_data_processing', 'manual__2024-09-19T09:13:25.420482+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmp9_cnaqij']
[2024-09-19T09:28:01.803+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask run_data_processing
[2024-09-19T09:28:01.806+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=387) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-19T09:28:01.807+0000] {standard_task_runner.py:72} INFO - Started process 388 to run task
[2024-09-19T09:28:01.856+0000] {task_command.py:467} INFO - Running <TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T09:13:25.420482+00:00 [running]> on host 76dded199c5f
[2024-09-19T09:28:01.965+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T09:13:25.420482+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-19T09:13:25.420482+00:00'
[2024-09-19T09:28:01.966+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T09:28:01.995+0000] {docker.py:367} INFO - Starting docker container from image us-west1-docker.pkg.dev/nba-fantasy-ml/nba-data-pipeline-repo/data-processing:latest
[2024-09-19T09:28:02.005+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-19T09:28:02.837+0000] {docker.py:438} INFO - 2024-09-19 09:28:02,835 - INFO - Starting data processing...
[2024-09-19T09:28:02.840+0000] {docker.py:438} INFO - 2024-09-19 09:28:02,839 - INFO - Database connected.
[2024-09-19T09:28:02.841+0000] {docker.py:438} INFO - 2024-09-19 09:28:02,839 - INFO - Cleaning and preprocessing data...
[2024-09-19T09:28:02.878+0000] {docker.py:438} INFO - 2024-09-19 09:28:02,876 - INFO - Validation passed.
[2024-09-19T09:28:02.878+0000] {docker.py:438} INFO - 2024-09-19 09:28:02,877 - INFO - Assigning unique IDs for players and games...
[2024-09-19T09:28:02.957+0000] {docker.py:438} INFO - 2024-09-19 09:28:02,955 - INFO - Inserting player stats into database...
[2024-09-19T09:28:03.053+0000] {docker.py:438} INFO - 2024-09-19 09:28:03,052 - INFO - Data processing completed successfully.
[2024-09-19T09:28:03.054+0000] {docker.py:438} INFO - 2024-09-19 09:28:03,052 - INFO - Database connection closed.
[2024-09-19T09:28:03.054+0000] {docker.py:438} INFO - 2024-09-19 09:28:03,052 - INFO - Successfully processed player_box_scores/2023-24/nba_player_stats_2023-24_2023-10-24_to_2023-10-25_2024-09-19_09-28-00.csv
[2024-09-19T09:28:03.313+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T09:28:03.314+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=run_data_processing, run_id=manual__2024-09-19T09:13:25.420482+00:00, execution_date=20240919T091325, start_date=20240919T092801, end_date=20240919T092803
[2024-09-19T09:28:03.346+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T09:28:03.367+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-19T09:28:03.369+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
